version: "2.1"

x-basic-setting: &basic-setting
  init: true
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "2G"
      max-file: "2"
      compress: "true"

networks:
  wireguard:
    name: wireguard
    driver: bridge

services:
  wireguard:
    <<: *basic-setting
    image: docker.io/linuxserver/wireguard:latest
    container_name: wireguard
    networks:
      - wireguard
    expose:
      - 51820/udp
    ports:
      - 0.0.0.0:51820:51820/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
     #- SERVERURL=wireguard.domain.com #option
      - SERVERPORT=51820 #optional
      - PEERS=pc,phone #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./config:/config:rw
      - /lib/modules:/lib/modules:rw
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
