version: "3"

x-basic-setting: &basic-setting
  init: true
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "2G"
      max-file: "2"
      compress: "true"
  healthcheck:
    test: [ "CMD-SHELL", "curl --fail http://localhost" ]
    interval: 30s
    timeout: 30s
    start_period: 10s
    retries: 3

volumes:
  my-volume:
    name: my-volume
    driver: local

networks:
  my-network:
    name: my-network
    driver: bridge
    internal: true

services:
  my-app:
    <<: *basic-setting
    image: docker.io/library/nginx:alpine
    container_name: my-app
    networks:
      - my-network
    expose:
      - 80
    ports:
      - 80:80
    environment:
      - foo=bar
    volumes:
      - my-volume:/etc/nginx:rw
